### ISSUE TITLE
Get rid of Deprecation warnings

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#448]
Alerts are found here: 
https://github.com/nci-hcmi-catalog/portal/network/alerts 

We need to resolve them.

**Comment by joneubank** [comment]
Upgrades and removals were made to several pacakges.

`react-scripts` was moved to be a dev-dependency, which should've fixed the `wepack-dev-server` and `serialize-javascript` package warnings but they continued to be reported. I dismissed these two warnings with the "code is not used" reasoning since they are only used in dev environment, not in production.
