### ISSUE TITLE
Bulk Upload (Google Sheets integration) tool needs to account for new fields

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#489]
- Template and validation needs to be updated with new fields
- Bulk uploader needs to accept new fields.

**Comment by joneubank** [comment]
Updates made to the Google Sheet Template: https://docs.google.com/spreadsheets/d/1x5IHiP-75erkvPEoBc0xvBZSpru2ptRiiLMS8ylBZhM/edit#gid=1107755039

**Comment by touhidulmridha** [comment]
Thanks Jon @joneubank  -  Bulk Upload Sheet downloads from your zenhub link: https://docs.google.com/spreadsheets/d/1x5IHiP-75erkvPEoBc0xvBZSpru2ptRiiLMS8ylBZhM/edit#gid=1107755039 ...but getting errors when uploading via frontend. 

Screenshot of error:
![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/f7ae3b4c-6278-4d25-9d11-70e70b2f8347)

Note: The frontend field updates were not reflected in the actual sheet...will log a separate ticket for that.

**Comment by touhidulmridha** [comment]
Update: Thanks @joneubank ...Just re-tried uploading and looks good so far.

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/43085282-0afc-481b-9103-7ba11e0ac5b6)

**Comment by joneubank** [comment]
None of the fields that are dependent on the Clinical Tumor Diagnosis have an enum list or drop down. Your issue would also apply to `Site of Sample Acquisition`, `Tumor Histological Grade`, `Clinical Stage Grouping`.

Leaving these without a dropdown was probably intentional as there is no clear list of all available options.. the options to use are based on the Diagnosis. If you can find the complete list of values I can add them to the data validation, otherwise lets leave this as is.

**Comment by rosibaj** [comment]
@joneubank Yes you are correct - these are left blank in the template bc there was not a way to make this happen in the Template sheet due to data dependencies. 
the IF this THEN this enum list is not possible in Google sheets - Eva is aware of this and does not require that in the template. 

@touhidulmridha @joneubank this is not something we have to address.

**Comment by touhidulmridha** [comment]
@rosibaj @joneubank - I just used Histological Type as an example...but understood, thanks.

**Comment by touhidulmridha** [comment]
Looks good now, thanks.

**Comment by rosibaj** [comment]
This has been tested and bulk upload for both Models and Variants is working correctltly in the dev environment.  Thanks for the work @joneubank !!
