### ISSUE TITLE
Make the default view of the catalog "expanded" models only without displaying the query

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#697]
- Default filter which requires a customization to arranger to have the default view showing only the expanded models without displaying the query along the top.

**Comment by mistryrn** [comment]
@rosibaj @joneubank I took a look at where we’re using the sqon on HCMI, got a few questions about certain scenarios that might have an effect on the expanded/unexpanded “hidden” sqon:

1. When the user clicks the “CLEAR” button on the top of the search page (assuming they have selected some other filters to make it show up), should that reset to only showing expanded models? Or should that respect whichever state their toggle is on?

2. On that note, when the user clicks on the toggle to show unexpanded models, should that appear in that top filter bar thing? This could be tricky, since technically when they click to show unexpanded models, we’re actually removing the filter to show only expanded models

3. When the user clicks on a "Yes (X)" link in the "Has Multiple Models" column of the table, it filters the table to show each of the linked models. Should that respect the expanded/unexpanded toggle? Or show all of the linked models, regardless of expansion status?

4. On the "Variants" table of the Model Details page, there is a "Frequency" link beside each variant. Clicking on that routes the user back to the search page, with a sqon that shows models with that variant. Should this show all models with that variant, or only expanded ones by default?

**Comment by joneubank** [comment]
@rosibaj correct me where I'm wrong but I'll answer with my own understanding:

1. Clear button has nothing to do with expanded toggle, no interaction here. Toggle stays as it was when clear is hit.
2. The toggle should not change what is shown in the filter bar. Filter bar is all the applied filters and then we secretly add a filter for "expanded only" if the toggle is off. When toggle on, we just don't apply this filter.
3. This is a bit tricky... the multiple models property which gives the lsit of models in the set isn't being filtered for expanded/unexpanded. I would say no, show them all.
4. Only expanded by default.

# 4 raises an intersting question about returning to the search page... if they have enabled the toggle to show unexpanded then refresh the page our filter would reset by default. Maybe we should use a localStorage property to record if the user has enabled or disabled the toggle and to use that setting when teh search page loads?

**Comment by rosibaj** [comment]
Default filter is showing correctly: 
![image](https://user-images.githubusercontent.com/15824252/93505010-47449700-f8e8-11ea-8e35-d07c2eb0b58f.png)

with no filters, the expanded count on the toggle is also correct. 

This looks really good! thanks so much @mistryrn !
