### ISSUE TITLE
Hover bubbles: Search Page facet headers

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#907]
- [ ] All of these hover bubbles also show within the catalog table header and facet panel. (note the facet panel ones looked odd being so wide but if this change is too much please ignore).

**Zeplin for Catalog hover bubbles**: https://zpl.io/be3Aeoz
![image](https://user-images.githubusercontent.com/18424138/115927719-dbfd0d80-a452-11eb-8200-e8c60629db80.png)

**Comment by kcullion** [comment]
@mistryrn I just noticed on the table hover bubbles, the link isn't using the usual red global style
![image](https://user-images.githubusercontent.com/18424138/118505945-e2ea0980-b6fa-11eb-87eb-9858fba5edbe.png)

**Comment by mistryrn** [comment]
@kcullion good catch! I'll get a quick fix in for that

**Comment by kcullion** [comment]
Some things I found with the facet header hover bubbles:

- [ ] The tooltip is getting cut off (because  of browser scrollbar)
![image (69)](https://user-images.githubusercontent.com/18424138/119043208-ccf07900-b986-11eb-9894-99c37680fc3e.png)

- [ ] The search results need to go on top of the ? icon for the hover bubble
![image](https://user-images.githubusercontent.com/18424138/119043313-e8f41a80-b986-11eb-8544-a2999864db22.png)

- [ ] could be related...interacting with this type of facet crashes the browser
![Uploading image.png…]()
