### ISSUE TITLE
Chemotherapeutic drug is getting "--" in the Cart Downloaded TSV when it should be a value of "No"

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#929]
Export of my models list cart: in TVS file, the Chemotherapeutic drug list available (yes/no) column, data is "--" and does not reflect the "No" for the specific models. 

This only looks to be happening on the "Cart Download" and not the main default export TSV on the table itself. This discrepancy between the downloads is reproducible in our testing environment.

**Comment by mistryrn** [comment]
After re-testing feedback point #4 using the cart export instead of table export:
* the issue of `No` for Chemotherapeutic Drug List Available being exported as `--` is present in collab, HCMI staging (and likely HCMI dev as well, though I haven’t tested it)
* it is not present on prod using the older cart export
* it looks related to feedback point #5, as fields that are `Yes` are being exported from the cart as `TRUE`, suggesting the exporter sees the `No` as a boolean `false` and inserts a `--`

Summary of current cart export for boolean values:
* `Yes` are now being exported as `TRUE`
* `No` are now being exported as `--`
* ` ` are being exported as `--`

**Comment by mistryrn** [comment]
Addressed in: https://github.com/nci-hcmi-catalog/portal/commit/4ba2a138af109db8116df267a309f893b41148e6

**Comment by akachru-github** [comment]
Exported HCM-BROD-0008-C25 via the Cart Download and saw that "Chemotheraputic Drug List Available" field contains the value of "No" instead of "--". 

Also checked this with the regular table export and noticed that it also contains the value of "No". 

This looks to have been fixed.
